include:
  - ci/docker-template.yml
  - ci/node-test-template.yml

stages:
  - test
  - build
  - deploy

# Staging
test_node_staging:
  extends:
    - .test_node
  stage: test
  only:
    - master
    - merge_requests
  tags:
    - executor:docker
  script:
    - npm run test-ci

lint_node_staging:
  extends:
    - .test_node
  stage: test
  only:
    - master
    - merge_requests
  tags:
    - executor:docker
  script:
    - npm run lint

build_docker_staging:
  # Use the official docker image.
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose build

deploy_docker_staging:
  extends:
    - .deploy_docker
  stage: deploy
  only:
    - master
  tags:
    - executor:shell
